/**
 * Created by Ever on 23/01/2018.
 */
/*
* Feature : <A short but clear description of the feature being tested, it's a best practice to include the related issue number (#issueId)>
*/
@IsTest
private class DemoClass1Test {
    /*
    *Setup required data for all test methods.
    */
    @TestSetup
    static void setup() {

    }
    /*
 	* Scenario : <Explanation of the scenario goes here>
	*/
    static testMethod void test() {
        /*
        * Given <a set of initial conditions.>
        */

        /*
        * And <more initial conditions>
        */

        /*
        * When <some action is fired by the actor>
        */

        /*
        * Then <a testeable output should be generated>
        */

        /*
        * And <any other output variables>
        */

        /*
        * And <more output variables>
        */
    }
}